# -*- coding: utf-8 -*-
"""Sistem-panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvhmDIEiH-YzNiK1k7PY3iASVy-5uP-Y
"""

def hitung_total_hasil(panen):
    return sum(panen)


hasil_panen = [100, 150, 200]

total = hitung_total_hasil(hasil_panen)

print("=== Sistem Pencatatan Hasil Panen ===")
print("Data hasil panen:", hasil_panen, "kg")
print("Total hasil panen:", total, "kg")